"""Nested TRAQID temporal-tabular atmospheric-background ensemble.

This reproduces the five-day MUMMA ensemble design on TRAQID.  For each
complete-date outer fold and each atmospheric product:

1. A ResNet50-GRU temporal branch predicts the local PM2.5 increment.
2. Its validation residual correction is cross-fitted by acquisition date.
3. An independent ExtraTrees tabular branch predicts the same local increment
   from non-PM engineered features.
4. A convex temporal/tabular weight is selected using validation predictions.
5. The selected weight is frozen and evaluated on the untouched outer test
   dates.  A fixed 50:50 ensemble is retained as a diagnostic.

The script reuses the GRU and corrected outer-test predictions generated by
``traqid_background_outer_crossfit``; it does not retrain the image models.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold

from pipelines.image_embeddings.traqid_background_outer_crossfit import (
    VARIANTS,
    attach_predictions,
    canonicalize,
    metrics,
)
from pipelines.image_embeddings.traqid_random_background_comparison import (
    residual_columns,
)
from pipelines.pm25_prediction.mumma_7day.model_current_data import estimators
from pipelines.pm25_prediction.mumma_7day.run_nested_background_ensemble import (
    conformal_radius,
    group_crossfit_convex_predictions,
)


ATMOSPHERIC_VARIANTS = ("cams", "merra2")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--background-outer-run",
        required=True,
        help="Completed output from traqid_background_outer_crossfit.",
    )
    parser.add_argument(
        "--sequence-manifest",
        default=(
            "experiments/traqid_pretraining_v1/data/processed/"
            "paper_style_sequences/"
            "traqid_paper_style_T7_front_sequence_manifest_time_balanced_purged.csv"
        ),
    )
    parser.add_argument(
        "--engineered-table",
        default=(
            "experiments/traqid_pretraining_v1/data/processed/"
            "traqid_engineered_T7_sequence_table.csv"
        ),
    )
    parser.add_argument("--background-csv", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--cell", choices=["gru", "lstm"], default="gru")
    parser.add_argument(
        "--variants",
        nargs="+",
        choices=ATMOSPHERIC_VARIANTS,
        default=list(ATMOSPHERIC_VARIANTS),
        help="Atmospheric backgrounds to evaluate.",
    )
    parser.add_argument("--tabular-model", default="extra_trees")
    parser.add_argument("--inner-group-folds", type=int, default=5)
    parser.add_argument(
        "--interval-alpha",
        type=float,
        default=0.10,
        help="Miscoverage level for date-grouped conformal intervals.",
    )
    parser.add_argument("--max-folds", type=int)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def optimal_convex_weight(
    truth: np.ndarray,
    temporal: np.ndarray,
    tabular: np.ndarray,
) -> float:
    """Return the MSE-optimal temporal weight constrained to [0, 1]."""
    difference = np.asarray(temporal, dtype=float) - np.asarray(
        tabular, dtype=float
    )
    denominator = float(np.dot(difference, difference))
    if denominator <= np.finfo(float).eps:
        return 0.5
    numerator = np.dot(
        difference,
        np.asarray(truth, dtype=float) - np.asarray(tabular, dtype=float),
    )
    return float(np.clip(float(numerator / denominator), 0.0, 1.0))


def crossfit_temporal_correction(
    validation: pd.DataFrame,
    features: list[str],
    *,
    actual_column: str,
    predicted_column: str,
    background_column: str,
    correction_name: str,
    folds: int,
    seed: int,
) -> np.ndarray:
    """Cross-fit validation residual correction by complete date."""
    groups = validation["date"].astype(str).to_numpy()
    unique_groups = np.unique(groups)
    n_splits = min(folds, len(unique_groups))
    if n_splits < 2:
        raise ValueError(
            "Temporal validation correction requires at least two dates"
        )
    actual_local = validation[actual_column].to_numpy(dtype=float)
    predicted_local = validation[predicted_column].to_numpy(dtype=float)
    residual = actual_local - predicted_local
    corrected_local = np.full(len(validation), np.nan, dtype=float)
    splitter = GroupKFold(n_splits=n_splits)
    for inner_fold, (train_index, held_index) in enumerate(
        splitter.split(validation, groups=groups),
        start=1,
    ):
        candidates = estimators(seed + inner_fold)
        if correction_name not in candidates:
            raise ValueError(
                f"Unknown temporal correction model: {correction_name}"
            )
        model = candidates[correction_name]
        model.fit(validation.iloc[train_index][features], residual[train_index])
        corrected_local[held_index] = (
            predicted_local[held_index]
            + model.predict(validation.iloc[held_index][features])
        )
    if np.isnan(corrected_local).any():
        raise RuntimeError("Cross-fitting left validation rows unpredicted")
    return (
        corrected_local
        + validation[background_column].to_numpy(dtype=float)
    )


def attach_engineered(
    manifest: pd.DataFrame,
    engineered: pd.DataFrame,
    features: list[str],
) -> pd.DataFrame:
    return manifest.merge(
        engineered[["sequence_id", *features]],
        on="sequence_id",
        validate="one_to_one",
    )


def main() -> int:
    args = parse_args()
    if not 0.0 < args.interval_alpha < 1.0:
        raise ValueError("--interval-alpha must be strictly between zero and one")
    background_run = Path(args.background_outer_run)
    output = Path(args.output_dir)
    output.mkdir(parents=True, exist_ok=True)

    canonical = canonicalize(pd.read_csv(args.sequence_manifest))
    engineered = pd.read_csv(args.engineered_table)
    if engineered["sequence_id"].duplicated().any():
        raise ValueError("Engineered table sequence_id must be unique")
    features = residual_columns(engineered)
    forbidden = [
        column
        for column in features
        if any(token in column.lower() for token in ("pm2.5", "pm10", "aqi"))
    ]
    if forbidden:
        raise ValueError(f"Target-proxy tabular features selected: {forbidden}")
    (output / "tabular_feature_columns.txt").write_text(
        "\n".join(features) + "\n"
    )

    background = pd.read_csv(args.background_csv)
    background["sample_id"] = background["sample_id"].astype(str)
    if background["sample_id"].duplicated().any():
        raise ValueError("Background sample_id must be unique")
    background = background.set_index("sample_id")

    outer_predictions = pd.read_csv(background_run / "predictions.csv")

    prediction_tables: list[pd.DataFrame] = []
    validation_rows: list[dict[str, object]] = []
    fold_rows: list[dict[str, object]] = []
    uncertainty_rows: list[dict[str, object]] = []

    for variant in args.variants:
        background_column = str(VARIANTS[variant]["background_column"])
        correction_name = str(VARIANTS[variant]["correction_model"])
        if background_column not in background.columns:
            raise ValueError(
                f"Background table lacks {background_column}"
            )
        variant_folds = sorted(
            (background_run / variant).glob("fold_*"),
            key=lambda path: int(path.name.split("_")[-1]),
        )
        if args.max_folds:
            variant_folds = variant_folds[: args.max_folds]
        if not variant_folds:
            raise ValueError(
                f"No completed folds found for {variant}: {background_run}"
            )

        for fold_dir in variant_folds:
            fold = int(fold_dir.name.split("_")[-1])
            manifest = pd.read_csv(fold_dir / "sequence_manifest.csv")
            manifest["target_sample_id"] = manifest[
                "target_sample_id"
            ].astype(str)
            manifest["date"] = manifest["date"].astype(str)
            manifest["_background"] = manifest[
                "target_sample_id"
            ].map(background[background_column])
            if manifest["_background"].isna().any():
                raise ValueError(
                    f"{variant} fold {fold}: missing atmospheric background"
                )
            target = f"target_PM2.5_{variant}_local_increment"
            manifest[target] = (
                manifest["target_PM2.5"].to_numpy(dtype=float)
                - manifest["_background"].to_numpy(dtype=float)
            )

            validation = attach_predictions(
                fold_dir / args.cell / "predictions_val.csv",
                manifest,
                engineered,
                features,
                target=target,
            )
            actual_column = f"actual_{target}"
            predicted_column = f"predicted_{target}"
            temporal_validation = crossfit_temporal_correction(
                validation,
                features,
                actual_column=actual_column,
                predicted_column=predicted_column,
                background_column="_background",
                correction_name=correction_name,
                folds=args.inner_group_folds,
                seed=args.seed + 1000 * fold,
            )

            attached = attach_engineered(manifest, engineered, features)
            training = attached[
                attached["outer_split"].eq("train")
            ].copy()
            validation_rows_table = attached[
                attached["outer_split"].eq("val")
            ].copy()
            validation_order = validation.set_index("sequence_id").index
            validation_rows_table = (
                validation_rows_table.set_index("sequence_id")
                .loc[validation_order]
                .reset_index()
            )

            tabular_candidates = estimators(args.seed + fold)
            if args.tabular_model not in tabular_candidates:
                raise ValueError(
                    f"Unknown tabular model: {args.tabular_model}"
                )
            tabular_model = tabular_candidates[args.tabular_model]
            tabular_model.fit(
                training[features],
                training[target].to_numpy(dtype=float),
            )
            tabular_validation = (
                validation_rows_table["_background"].to_numpy(dtype=float)
                + tabular_model.predict(validation_rows_table[features])
            )
            validation_truth = (
                validation[actual_column].to_numpy(dtype=float)
                + validation["_background"].to_numpy(dtype=float)
            )
            if not np.allclose(
                validation_truth,
                validation_rows_table["target_PM2.5"].to_numpy(dtype=float),
            ):
                raise ValueError(
                    f"{variant} fold {fold}: validation targets disagree"
                )
            weight = optimal_convex_weight(
                validation_truth,
                temporal_validation,
                tabular_validation,
            )
            validation_selected = (
                weight * temporal_validation
                + (1.0 - weight) * tabular_validation
            )
            validation_selected_crossfit = group_crossfit_convex_predictions(
                validation_truth,
                temporal_validation,
                tabular_validation,
                validation["date"].astype(str).to_numpy(),
            )
            calibration_predictions = {
                "temporal_branch": temporal_validation,
                "tabular_branch": tabular_validation,
                "validation_selected_weight": validation_selected_crossfit,
                "fixed_equal_weight_diagnostic": (
                    0.5 * temporal_validation + 0.5 * tabular_validation
                ),
            }
            interval_radii = {
                method: conformal_radius(
                    validation_truth,
                    calibration_prediction,
                    alpha=args.interval_alpha,
                )
                for method, calibration_prediction
                in calibration_predictions.items()
            }
            validation_rows.append(
                {
                    "variant": variant,
                    "fold": fold,
                    "validation_dates": "|".join(
                        sorted(validation["date"].unique())
                    ),
                    "n_validation": len(validation),
                    "temporal_weight": weight,
                    **{
                        f"temporal_{key}": value
                        for key, value in metrics(
                            validation_truth, temporal_validation
                        ).items()
                    },
                    **{
                        f"tabular_{key}": value
                        for key, value in metrics(
                            validation_truth, tabular_validation
                        ).items()
                    },
                    **{
                        f"selected_{key}": value
                        for key, value in metrics(
                            validation_truth, validation_selected
                        ).items()
                    },
                }
            )

            # After the weight is frozen, refit the tabular branch on every
            # non-test sequence.  The outer-test targets remain untouched.
            development = attached[
                ~attached["outer_split"].eq("test")
            ].copy()
            final_tabular = estimators(args.seed + 100 + fold)[
                args.tabular_model
            ]
            final_tabular.fit(
                development[features],
                development[target].to_numpy(dtype=float),
            )
            test_rows = attached[
                attached["outer_split"].eq("test")
            ].copy()
            tabular_test = (
                test_rows["_background"].to_numpy(dtype=float)
                + final_tabular.predict(test_rows[features])
            )

            temporal_test = outer_predictions[
                outer_predictions["variant"].eq(variant)
                & outer_predictions["fold"].eq(fold)
                & outer_predictions["model"].eq(correction_name)
            ][
                [
                    "sequence_id",
                    "date",
                    "actual_PM2.5",
                    "predicted_PM2.5",
                ]
            ].rename(
                columns={"predicted_PM2.5": "temporal_prediction"}
            )
            test_order = test_rows.set_index("sequence_id").index
            temporal_test = (
                temporal_test.set_index("sequence_id")
                .loc[test_order]
                .reset_index()
            )
            truth = temporal_test["actual_PM2.5"].to_numpy(dtype=float)
            if not np.allclose(
                truth, test_rows["target_PM2.5"].to_numpy(dtype=float)
            ):
                raise ValueError(
                    f"{variant} fold {fold}: outer-test targets disagree"
                )
            temporal_test_values = temporal_test[
                "temporal_prediction"
            ].to_numpy(dtype=float)
            selected_test = (
                weight * temporal_test_values
                + (1.0 - weight) * tabular_test
            )
            fixed_test = 0.5 * (temporal_test_values + tabular_test)

            methods = {
                "temporal_branch": temporal_test_values,
                "tabular_branch": tabular_test,
                "validation_selected_weight": selected_test,
                "fixed_equal_weight_diagnostic": fixed_test,
            }
            for method, prediction in methods.items():
                radius = interval_radii[method]
                interval_lower = prediction - radius
                interval_upper = prediction + radius
                covered = (
                    (truth >= interval_lower) & (truth <= interval_upper)
                )
                fold_rows.append(
                    {
                        "variant": variant,
                        "fold": fold,
                        "test_dates": "|".join(
                            sorted(temporal_test["date"].unique())
                        ),
                        "method": method,
                        "temporal_weight": (
                            1.0
                            if method == "temporal_branch"
                            else 0.0
                            if method == "tabular_branch"
                            else 0.5
                            if method == "fixed_equal_weight_diagnostic"
                            else weight
                        ),
                        "n_test": len(truth),
                        **metrics(truth, prediction),
                    }
                )
                uncertainty_rows.append(
                    {
                        "variant": variant,
                        "fold": fold,
                        "test_dates": "|".join(
                            sorted(temporal_test["date"].unique())
                        ),
                        "method": method,
                        "alpha": args.interval_alpha,
                        "nominal_coverage": 1.0 - args.interval_alpha,
                        "n_calibration": len(validation_truth),
                        "calibration_dates": int(
                            validation["date"].nunique()
                        ),
                        "interval_radius": radius,
                        "interval_width": 2.0 * radius,
                        "n_test": len(truth),
                        "test_coverage": float(np.mean(covered)),
                    }
                )
                prediction_tables.append(
                    pd.DataFrame(
                        {
                            "sequence_id": temporal_test["sequence_id"],
                            "date": temporal_test["date"],
                            "variant": variant,
                            "fold": fold,
                            "method": method,
                            "actual_PM2.5": truth,
                            "predicted_PM2.5": prediction,
                            "interval_alpha": args.interval_alpha,
                            "interval_radius": radius,
                            "interval_lower": interval_lower,
                            "interval_upper": interval_upper,
                            "interval_covered": covered,
                            "temporal_weight": (
                                0.5
                                if method
                                == "fixed_equal_weight_diagnostic"
                                else weight
                                if method
                                == "validation_selected_weight"
                                else 1.0
                                if method == "temporal_branch"
                                else 0.0
                            ),
                        }
                    )
                )

    folds = pd.DataFrame(fold_rows)
    folds.to_csv(output / "metrics_by_fold.csv", index=False)
    pd.DataFrame(validation_rows).to_csv(
        output / "validation_weight_audit.csv", index=False
    )
    predictions = pd.concat(prediction_tables, ignore_index=True)
    predictions.to_csv(output / "predictions.csv", index=False)
    uncertainty = pd.DataFrame(uncertainty_rows)
    uncertainty.to_csv(output / "uncertainty_by_fold.csv", index=False)

    aggregate_rows: list[dict[str, object]] = []
    for (variant, method), group in predictions.groupby(
        ["variant", "method"]
    ):
        matching = folds[
            folds["variant"].eq(variant)
            & folds["method"].eq(method)
        ]
        aggregate_rows.append(
            {
                "variant": variant,
                "method": method,
                "n_test": len(group),
                **metrics(
                    group["actual_PM2.5"].to_numpy(dtype=float),
                    group["predicted_PM2.5"].to_numpy(dtype=float),
                ),
                "mean_fold_mae": float(matching["mae"].mean()),
                "mean_fold_rmse": float(matching["rmse"].mean()),
                "mean_fold_r2": float(matching["r2"].mean()),
                "worst_fold_rmse": float(matching["rmse"].max()),
                "temporal_weight_mean": float(
                    matching["temporal_weight"].mean()
                ),
            }
        )
    aggregate = pd.DataFrame(aggregate_rows).sort_values(
        ["r2", "rmse"], ascending=[False, True]
    )
    aggregate.to_csv(output / "metrics_aggregate.csv", index=False)
    uncertainty_aggregate = (
        predictions.groupby(["variant", "method"], as_index=False)
        .agg(
            n_test=("interval_covered", "size"),
            empirical_coverage=("interval_covered", "mean"),
            mean_interval_width=(
                "interval_radius",
                lambda value: float(2.0 * value.mean()),
            ),
            worst_fold_radius=("interval_radius", "max"),
        )
        .sort_values(
            ["variant", "empirical_coverage"],
            ascending=[True, False],
        )
    )
    uncertainty_aggregate.to_csv(
        output / "uncertainty_aggregate.csv", index=False,
    )

    run = {
        "dataset": "TRAQID",
        "protocol": "five-fold complete-date outer holdout",
        "architecture": (
            "atmospheric background + temporal local-increment branch + "
            "independent tabular local-increment branch"
        ),
        "variants": list(args.variants),
        "tabular_model": args.tabular_model,
        "tabular_feature_count": len(features),
        "temporal_corrections": {
            variant: VARIANTS[variant]["correction_model"]
            for variant in ATMOSPHERIC_VARIANTS
        },
        "ensemble_weight_selection": (
            "MSE-optimal convex weight selected on cross-fitted outer-"
            "validation predictions only"
        ),
        "fixed_equal_weight_is_diagnostic": True,
        "uncertainty": {
            "method": "symmetric absolute-residual conformal interval",
            "alpha": args.interval_alpha,
            "nominal_coverage": 1.0 - args.interval_alpha,
            "calibration_partition": "outer-validation sequences only",
            "calibration_group": "acquisition date",
            "validation_selected_weight_calibration": (
                "leave-one-date-out weight cross-fitted predictions"
            ),
            "outer_test_targets_used_for_interval_calibration": False,
            "caveat": (
                "Coverage remains exploratory because the architecture was "
                "developed after inspection of TRAQID."
            ),
        },
        "background_target_fitted": False,
        "pm_aqi_predictors_used": False,
        "reportable_as_unseen_date_generalization": True,
        "exploratory": True,
        "reason": (
            "The architecture was developed after earlier inspection of this "
            "dataset; final confirmation requires untouched future dates."
        ),
        "seed": args.seed,
    }
    (output / "run.json").write_text(json.dumps(run, indent=2) + "\n")
    print("\nTRAQID NESTED BACKGROUND ENSEMBLES\n")
    print(aggregate.to_string(index=False))
    print("\nVALIDATION-CALIBRATED UNCERTAINTY\n")
    print(uncertainty_aggregate.to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
